Add operation name attribute on gateway.plan spans
apollographql/federation pull request #2807
Opened 2023-10-04 21:47 UTC by theJC

Addresses https://github.com/apollographql/federation/issues/2802

Add operation name to gateway.plan span

2023-10-05 16:18 UTC, trevor-scheer requested changes

2023-10-05 21:12 UTC, theJC commented on gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
> +          "graphql.document": "#graphql\\n      subscription GetProduct($upc: String!) {\\n        product(upc: $upc) {\\n          name\\n        }\\n      }\\n    "
great idea/feedback, thank you.

2023-10-05 21:31 UTC, theJC commented on gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
> +          "graphql.document": "#graphql\\n      subscription GetProduct($upc: String!) {\\n        product(upc: $upc) {\\n          name\\n        }\\n      }\\n    "
Should now be addressed with most recent commit

2023-10-06 14:58 UTC, theJC commented
When making changes like this in the gateway, is the expectation we also attempt to make a similar change (as close as possible) in router?

2023-10-11 18:42 UTC, theJC commented on gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
> +          "graphql.document": "#graphql\\n      subscription GetProduct($upc: String!) {\\n        product(upc: $upc) {\\n          name\\n        }\\n      }\\n    "
@trevor-scheer  -- Anything else you'd like adjusted in this MR?  -Thanks

2023-10-12 01:35 UTC, trevor-scheer commented on gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
> +          "graphql.document": "#graphql\\n      subscription GetProduct($upc: String!) {\\n        product(upc: $upc) {\\n          name\\n        }\\n      }\\n    "
Hey @theJC, should be good to go. I'll take a final pass and merge next week when I'm back from Summit.

2023-10-20 22:34 UTC, trevor-scheer approved these changes
Can you please run `npx changeset` and add a `minor` changeset? It can be a fairly short description explaining what's added to the span.

Thanks!

2023-10-20 22:51 UTC, trevor-scheer commented
@theJC generally speaking, yes. I should have a better answer for you next week in this particular case.

2023-10-21 00:53 UTC, theJC commented
Changeset added. prettier code format issue with my updates to the tests fixed as well.

2023-10-23 17:05 UTC, trevor-scheer approved these changes
Thanks for your work on this @theJC!

2023-10-23 17:05 UTC, merged

2023-10-24 19:00 UTC, trevor-scheer commented
@theJC in this particular case, we don't intend to maintain parity with the router. The router team is currently working on a more robust solution to configuring otel.
https://github.com/apollographql/router/pull/4061