Add missing typing support to make-fetch-happen.d.ts
apollographql/federation pull request #316
Opened 2021-01-05 05:54 UTC by michael-watson

Add `cert`, `key`, `proxy` and `noProxy` options to `make-fetch-happen` typings to support internal security requirements around custom certs

2021-01-05 15:33 UTC, trevor-scheer requested changes
Left some suggestions. Noting that these are incomplete but definitely an improvement! These will be replaced / removed entirely when @abernix is able to land his `DefinitelyTyped` PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50339.

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    noProxy?: string;
```suggestion
    noProxy?: string | string[];
```

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    proxy?: string;
```suggestion
    proxy?: string | URL;
```

We'll also need to add the proper import at the top:
`import { URL } from 'url';`

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    key?: string;
```suggestion
    cert?: SecureContextOptions['cert'];
    key?: SecureContextOptions['key'];
```
We'll also need to add the proper import at the top:
`import { SecureContextOptions } from 'tls';`

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    key?: string;
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tls.d.ts#L563

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    noProxy?: string;
Ref: https://github.com/npm/make-fetch-happen#opts-no-proxy

2021-01-05 15:33 UTC, trevor-scheer commented on gateway-js/src/make-fetch-happen.d.ts
> +    proxy?: string;
Ref: https://github.com/npm/make-fetch-happen#opts-proxy

2021-01-05 15:34 UTC, trevor-scheer commented
Please add a changelog entry, address comments and this will be good to go. Thanks @michael-watson!

2021-03-04 10:29 UTC, abernix commented
Going to close this in favor of using the DefinitelyTyped-published types [which already include these missing properties](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d73fdfc3ff6aed8f47bd4092ada9623bcc1f4fe8/types/make-fetch-happen/index.d.ts).

Someone still needs to open the PR to change this repository to rely on that `@types/make-fetch-happen` package (and remove these baked-in types from this repo), but that's being tracked in https://github.com/apollographql/federation/issues/535.

Thanks for opening this originally! (If there are additional updates, the PRs should be opened to DefinitelyTyped.)

2021-03-04 10:29 UTC, closed without merging