Update entities.md
apollographql/federation pull request #323
Opened 2021-01-12 21:30 UTC by brettfishman

There was no target defined for `#entity-migration`, but there is a `#type-migration` heading. I updated the links to target `Type Migration` instead so they work.

2021-01-12 21:30 UTC, apollo-cla commented
@brettfishman: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2021-01-13 19:35 UTC, trevor-scheer requested changes
Thanks @brettfishman! Let's update the verbage: entity -> type as well. I've added suggestions where appropriate.

2021-01-13 19:35 UTC, trevor-scheer commented on docs/source/entities.md
> +The steps for migrating an individual field are nearly identical in form to the steps for [migrating an entire entity](#type-migration).
```suggestion
The steps for migrating an individual field are nearly identical in form to the steps for [migrating an entire type](#type-migration).
```

2021-01-13 19:35 UTC, trevor-scheer commented on docs/source/entities.md
> +We can perform this migration safely with the following steps (_additional commentary on each step is provided in [Entity migration](#type-migration)_):
```suggestion
We can perform this migration safely with the following steps (_additional commentary on each step is provided in [Type migration](#type-migration)_):
```

2021-01-15 21:46 UTC, brettfishman commented
Thanks @trevor-scheer - this should be all set now. Apologies for the delay getting back to you!

2021-01-22 17:07 UTC, brettfishman commented
Hi @trevor-scheer - just following up on this. How's it looking?

2021-04-27 19:09 UTC, StephenBarlow approved these changes

2021-04-27 19:14 UTC, StephenBarlow commented
Sorry for the delay here @brettfishman! It looks like we reverted the language in this article, and the header is once again "entity migration". So I'll close this for now and then will make sure I'm more vigilant with these internal links if we switch it back! 😄

2021-04-27 19:14 UTC, closed without merging