Open telemetry support
apollographql/federation pull request #803
Opened 2021-06-09 16:47 UTC by BrynCooke

This PR adds instrumentation to emit the following spans:
* federation.request - total time to server a request.
* federation.validate - time to validate the federated query.
* federation.plan - time to plan the federated query.
* federation.execute - the total time executing query.
* federation.fetch - time fetching data from a subgraph.
* federation.postprocessing - time to render the response from all the subgraph data.

The instrumentation looks a little messy due to the requirement to set error status on spans on exception, but also if errors are added to the response.

2021-06-09 16:47 UTC, apollo-cla commented
@BrynCooke: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2021-06-11 02:18 UTC, trevor-scheer requested changes
This is looking really great! I don't have any majorly blocking issues, and I think my couple larger suggestions are optional/food for thought anyway.

One separate comment I will make is that consistency in style would be nice. Things that come to mind are indentation, bracket spacing, semicolons, and newlines. Note that this is explicitly not enforced on this repo and it's certainly not correct everywhere, either, so do with that what you will. It's not something I'll go around and leaving nitpick comments about or block on.

2021-06-11 13:54 UTC, BrynCooke commented on gateway-js/package.json
> +    "@opentelemetry/node": "^0.20.0"
Done

2021-06-11 13:55 UTC, BrynCooke commented on gateway-js/src/executeQueryPlan.ts
> +    span.setAttribute("sevice", fetch.serviceName);
Done

2021-06-11 13:55 UTC, BrynCooke commented on gateway-js/src/__tests__/gateway/opentelemetry.test.ts
> +      }
Done

2021-06-11 13:56 UTC, BrynCooke commented on federation-integration-testsuite-js/src/snapshotSerializers/readableSpanArraySerializer.ts
> +        });
I added some comments and also simplified the algorithm.
At least part of the issue was that I had named things badly. Hopefully it looks better now.

2021-06-11 14:08 UTC, trevor-scheer commented
I'm less familiar with the nuances of lockfiles generated by npm@7, but I would expect a diff caused by the move of the `devDependencies`. This change would be represented after running an `npm install` now that they're in the correct place within the `package.json` root. Can you please give that a run and see if there's any change?

2021-06-11 14:12 UTC, trevor-scheer approved these changes
Aside from my `package-lock.json` concern, this looks ready to me!

2021-06-11 14:12 UTC, trevor-scheer commented on gateway-js/CHANGELOG.md
> +- OpenTelemetry support PR TBA
Let's update this with the PR # and link. I think the description is fine but if you feel there's anything worth adding here that's great too.

2021-06-11 14:23 UTC, BrynCooke commented on gateway-js/src/index.ts
> +      }
I was also wondering about such a helper function. It seems strange that they didn't bake this in to the OpenTelemetry API.
startActiveSpan actually takes a bunch more parameters, and I realised that I should have been using one of these overloads at least once.

Let's leave it for now, but agree it's not pretty.

2021-06-11 14:26 UTC, trevor-scheer commented on gateway-js/src/index.ts
> +      }
Sgtm!

2021-06-11 14:33 UTC, BrynCooke commented
Thanks for all the feedback @trevor-scheer !

2021-06-11 14:58 UTC, merged