Add operationName variable for health_check_query
apollographql/federation pull request #837
Opened 2021-06-25 09:44 UTC by kutysam

This is with regards to https://github.com/apollographql/federation/issues/835

There is another issue that is slightly related https://github.com/apollographql/federation/issues/768 but the code is standalone for healthcheckquery, thus I am fixing this just for health check.

Why do we need this?
1. If you do a call with graphiql, you can see a operationName key being sent out too.
2. This operationName will be logged in metrics such as `gql.operation.name` in netflix dgs framework metrics https://netflix.github.io/dgs/advanced/instrumentation/#shared-tags
3. For us to filter out health check requests, we can use operationName to filter them out.

2021-06-25 09:44 UTC, apollo-cla commented
@kutysam: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2021-06-25 09:45 UTC, d2phap approved these changes

2021-06-25 16:01 UTC, kutysam commented
I've signed the agreement..
The ci is failing but I'm sure it is not due to my commit.

2021-06-25 16:49 UTC, trevor-scheer approved these changes
I've suggested we stick to the exact operation name with the double underscore convention. 
Otherwise, LGTM! Can you please add an entry to `gateway-js/CHANGELOG.md`?

2021-06-25 16:49 UTC, trevor-scheer commented on gateway-js/src/index.ts
> +export const HEALTH_CHECK_QUERY_OPERATION_NAME = 'ApolloServiceHealthCheck';
```suggestion
export const HEALTH_CHECK_QUERY_OPERATION_NAME = '__ApolloServiceHealthCheck__';
```

2021-06-25 20:15 UTC, glasser requested changes
Is this really necessary? See my comment: https://github.com/apollographql/federation/issues/835#issuecomment-868809776

If we suddenly have a pressing need to go above and beyond the standard GraphQL-over-HTTP protocol and always include operationName even when there's just one operation, then this would just be the tip of the iceberg. I'm sure there are hundreds of places across Apollo open source projects where we would need to make a similar change.

2021-07-20 22:34 UTC, glasser commented
Will fix #835 in #870.

2021-07-20 22:34 UTC, closed without merging